service: charleywong
app: charleywong
org: giffonio
frameworkVersion: ">=1.61.1"

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    binaryMediaTypes:
      - '*/*'

package:
  exclude:
    - .devcontainer/**
    - .github/**
    - .haxelib/**
    - .vscode/**
    - chrome/**
    - lib/**
    - src/**
    - test/**
    - '*.py'
    - '*.hxml'
    - chrome.*.js

functions:
  web:
    handler: index.handler
    events:
      - http:
          method: ANY
          path: '/'
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
