name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      selenium:
        image: selenium/standalone-chrome-debug:3.141.59-yttrium
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          set -ex
          sudo add-apt-repository ppa:haxe/haxe4.0
          sudo apt-get update -qqy
          sudo apt-get install -qqy git iproute2 procps sudo bash-completion build-essential haxe
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install -y nodejs=12.*
          pip3 install -r requirements.txt
          npm install
          haxelib newrepo
          haxelib install all --always
      - name: Compile index.js
        run: haxe build.hxml
      - name: Compile import.py
        run: haxe import.hxml
      - name: Run test
        run: haxe test.hxml
      - name: Test importer
        run: python3 import.py https://www.facebook.com/thebookcure.hk/posts/2729989220398638
        env:
          HUB_HOST: localhost
