name: CI

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: giffon/charleywong_devcontainer_workspace:20200127
    services:
      selenium:
        image: selenium/standalone-chrome-debug:3.141.59-yttrium
        ports:
          - 4444:4444
    env:
      HUB_HOST: selenium
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup Python virtualenv
        shell: bash
        run: |
          set -ex
          python3 -m virtualenv -p /usr/bin/python3.7 --no-pip ~/venv
          source ~/venv/bin/activate
          curl -sSLf https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py pip==19.3.1
          pip3 install -r requirements.txt
      - name: Install libraries
        run: |
          set -ex
          npm install
          haxelib newrepo
          haxelib install all --always
      - name: Export flexsearch index
        run: haxe exportFlexsearch.hxml
      - uses: actions/upload-artifact@v1
        with:
          name: flexsearch.json
          path: flexsearch.json
      - name: Compile index.js
        run: haxe build.hxml
      - uses: actions/upload-artifact@v1
        with:
          name: index.js
          path: index.js
      - name: Compile Chrome extension
        run: haxe chrome-extension.hxml
      - uses: actions/upload-artifact@v1
        with:
          name: chrome
          path: chrome
      - name: Run test
        shell: bash
        run: |
          source ~/venv/bin/activate
          haxe test.hxml "$GITHUB_EVENT_NAME"
  deploy:
    needs: build
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: giffon/charleywong_devcontainer_workspace:20200127
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/download-artifact@v1
        with:
          name: index.js
      - uses: actions/download-artifact@v1
        with:
          name: flexsearch.json
      - name: Install libraries
        run: |
          set -ex
          npm install
          haxelib newrepo
          haxelib install all --always
      - run: ls -lh
      - name: Deploy
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretAccessKey }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.serverlessAccessKey }}
      - name: Post-deployment test
        run: haxe test.hxml post-deployment
